// Code generated by Kitex v0.5.2. DO NOT EDIT.

package taskservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	task "summer/server/shared/kitex_gen/task"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	NewTask_(ctx context.Context, req *task.NewTaskRequest_, callOptions ...callopt.Option) (r *task.NewTaskResponse_, err error)
	GetTaskStatus(ctx context.Context, req *task.GetTaskStatusRequest, callOptions ...callopt.Option) (r *task.GetTaskStatusResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTaskServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTaskServiceClient struct {
	*kClient
}

func (p *kTaskServiceClient) NewTask_(ctx context.Context, req *task.NewTaskRequest_, callOptions ...callopt.Option) (r *task.NewTaskResponse_, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.NewTask_(ctx, req)
}

func (p *kTaskServiceClient) GetTaskStatus(ctx context.Context, req *task.GetTaskStatusRequest, callOptions ...callopt.Option) (r *task.GetTaskStatusResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTaskStatus(ctx, req)
}
